import os
from pathlib import Path
import duckdb
derived = Path(os.environ['MIMIC_DERIVED'])
source = derived / 'vasopressor_liberation_code_status_stage12.parquet'
output = derived / 'vasopressor_liberation_competing_outcomes_stage13.parquet'

def sql_path(path):
    return str(path).replace('\\', '/').replace("'", "''")
con = duckdb.connect()
con.execute('PRAGMA threads=1')
con.execute("PRAGMA memory_limit='8GB'")
con.execute(f"\nCREATE OR REPLACE TEMP TABLE stage13 AS\nWITH primary_cohort AS (\n    SELECT *\n    FROM read_parquet('{sql_path(source)}')\n    WHERE cmo_active_at_stop = 0\n),\nclassified AS (\n    SELECT\n        *,\n\n        CASE\n            WHEN restart_24h = 1 AND death_24h = 1\n            THEN 1 ELSE 0\n        END AS both_events_24h,\n\n        CASE\n            WHEN restart_24h = 1\n             AND death_24h = 1\n             AND next_episode_start = deathtime\n            THEN 1 ELSE 0\n        END AS simultaneous_events,\n\n        CASE\n            WHEN restart_24h = 0 AND death_24h = 0\n                THEN 'durable_liberation_alive'\n\n            WHEN restart_24h = 1 AND death_24h = 0\n                THEN 'restart_first'\n\n            WHEN restart_24h = 0 AND death_24h = 1\n                THEN 'death_first'\n\n            WHEN restart_24h = 1 AND death_24h = 1\n             AND next_episode_start < deathtime\n                THEN 'restart_first'\n\n            WHEN restart_24h = 1 AND death_24h = 1\n             AND deathtime < next_episode_start\n                THEN 'death_first'\n\n            WHEN restart_24h = 1 AND death_24h = 1\n             AND next_episode_start = deathtime\n                THEN 'simultaneous_restart_death'\n\n            ELSE 'unclassifiable'\n        END AS competing_outcome,\n\n        CASE\n            WHEN restart_24h = 1 AND death_24h = 0\n                THEN date_diff(\n                    'second', episode_end, next_episode_start\n                ) / 3600.0\n\n            WHEN restart_24h = 0 AND death_24h = 1\n                THEN date_diff(\n                    'second', episode_end, deathtime\n                ) / 3600.0\n\n            WHEN restart_24h = 1 AND death_24h = 1\n             AND next_episode_start <= deathtime\n                THEN date_diff(\n                    'second', episode_end, next_episode_start\n                ) / 3600.0\n\n            WHEN restart_24h = 1 AND death_24h = 1\n             AND deathtime < next_episode_start\n                THEN date_diff(\n                    'second', episode_end, deathtime\n                ) / 3600.0\n\n            ELSE NULL\n        END AS time_to_first_event_hours,\n\n        CASE\n            WHEN restart_24h = 1\n            THEN date_diff(\n                'second', episode_end, next_episode_start\n            ) / 3600.0\n            ELSE NULL\n        END AS time_to_restart_hours,\n\n        CASE\n            WHEN death_24h = 1\n            THEN date_diff(\n                'second', episode_end, deathtime\n            ) / 3600.0\n            ELSE NULL\n        END AS time_to_death_hours\n\n    FROM primary_cohort\n)\nSELECT\n    *,\n    CASE competing_outcome\n        WHEN 'durable_liberation_alive' THEN 0\n        WHEN 'restart_first' THEN 1\n        WHEN 'death_first' THEN 2\n        WHEN 'simultaneous_restart_death' THEN 3\n        ELSE 9\n    END AS competing_outcome_code\nFROM classified\n")
con.execute(f"\nCOPY stage13 TO '{sql_path(output)}'\n(FORMAT PARQUET, COMPRESSION ZSTD)\n")
qa = con.execute('\nSELECT\n    count(*) AS primary_stays,\n    sum(restart_24h) AS restart_24h,\n    sum(death_24h) AS death_24h,\n    sum(both_events_24h) AS both_events_24h,\n    sum(simultaneous_events) AS simultaneous_events,\n\n    sum(CASE\n        WHEN restart_24h = 1 AND next_episode_start IS NULL\n        THEN 1 ELSE 0 END\n    ) AS restart_missing_time,\n\n    sum(CASE\n        WHEN death_24h = 1 AND deathtime IS NULL\n        THEN 1 ELSE 0 END\n    ) AS death_missing_time,\n\n    sum(CASE\n        WHEN time_to_restart_hours < 0\n        THEN 1 ELSE 0 END\n    ) AS restart_before_cessation,\n\n    sum(CASE\n        WHEN time_to_death_hours < 0\n        THEN 1 ELSE 0 END\n    ) AS death_before_cessation,\n\n    sum(CASE\n        WHEN time_to_restart_hours > 24\n        THEN 1 ELSE 0 END\n    ) AS restart_after_24h,\n\n    sum(CASE\n        WHEN time_to_death_hours > 24\n        THEN 1 ELSE 0 END\n    ) AS death_after_24h\nFROM stage13\n').fetchdf()
outcomes = con.execute('\nSELECT\n    competing_outcome,\n    competing_outcome_code,\n    count(*) AS stays,\n    round(100.0 * count(*) / sum(count(*)) OVER (), 2) AS percent,\n    round(median(time_to_first_event_hours), 2) AS median_event_hours,\n    round(\n        quantile_cont(time_to_first_event_hours, 0.25), 2\n    ) AS p25_event_hours,\n    round(\n        quantile_cont(time_to_first_event_hours, 0.75), 2\n    ) AS p75_event_hours\nFROM stage13\nGROUP BY competing_outcome, competing_outcome_code\nORDER BY competing_outcome_code\n').fetchdf()
code_status = con.execute("\nSELECT\n    CASE\n        WHEN cmo_active_at_stop = 1 THEN 'CMO'\n        WHEN dnr_dni_active_at_stop = 1 THEN 'DNR/DNI'\n        WHEN code_status_documented_before_stop = 1 THEN 'Full/other'\n        ELSE 'Not documented'\n    END AS status_group,\n    count(*) AS stays,\n    sum(CASE WHEN competing_outcome = 'restart_first'\n             THEN 1 ELSE 0 END) AS restart_first,\n    sum(CASE WHEN competing_outcome = 'death_first'\n             THEN 1 ELSE 0 END) AS death_first\nFROM stage13\nGROUP BY status_group\nORDER BY stays DESC\n").fetchdf()
print('\nSTAGE 13 COMPETING OUTCOMES COMPLETED')
print('\nTEMPORAL QA')
print(qa.to_string(index=False))
print('\nCOMPETING OUTCOME DISTRIBUTION')
print(outcomes.to_string(index=False))
print('\nOUTCOMES BY PRE-CESSATION CODE STATUS')
print(code_status.to_string(index=False))
print(f'\nOutput: {output}')
con.close()
